import { NgModule } from '@angular/core';
import { DxButtonModule, DxChartModule, DxCheckBoxModule, DxCircularGaugeModule, DxColorBoxModule, DxDataGridModule, DxDateBoxModule, DxDiagramModule, DxFileManagerModule, DxFileUploaderModule, DxFormModule, DxGanttModule, DxHtmlEditorModule, DxLinearGaugeModule, DxListModule, DxNumberBoxModule, DxPieChartModule, DxPopoverModule, DxPopupModule, DxScrollViewModule, DxSelectBoxModule, DxSliderModule, DxSwitchModule, DxTabPanelModule, DxTemplateModule, DxTextAreaModule, DxTextBoxModule, DxTileViewModule, DxTreeViewModule, DxVectorMapModule } from 'devextreme-angular';
import RemoteFileSystemProvider from 'devextreme/file_management/remote_provider';
import { NotificationToolTip } from 'src/base/notificationToolTip';

@NgModule({
  declarations: [],
  imports: [
    DxDataGridModule,
    DxHtmlEditorModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxDiagramModule,
    DxChartModule,
    DxGanttModule,
    DxCircularGaugeModule,
    DxLinearGaugeModule,
    DxSliderModule,
    DxTabPanelModule,
    DxTreeViewModule,
    DxTemplateModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxColorBoxModule,
    DxNumberBoxModule,
    DxSwitchModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxDateBoxModule,
    DxFormModule,
    DxFileManagerModule,
    DxPopupModule,
    DxTextBoxModule,
    DxFileUploaderModule,
    DxButtonModule,
    DxTileViewModule,
    DxListModule,
    DxTemplateModule,
    DxPopupModule,
    DxPopoverModule,
    DxVectorMapModule,
    DxPieChartModule,
    DxScrollViewModule,
  ],
  exports: [
    DxDataGridModule,
    DxHtmlEditorModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxDiagramModule,
    DxChartModule,
    DxGanttModule,
    DxCircularGaugeModule,
    DxLinearGaugeModule,
    DxSliderModule,
    DxTabPanelModule,
    DxTreeViewModule,
    DxTemplateModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxColorBoxModule,
    DxNumberBoxModule,
    DxSwitchModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxDateBoxModule,
    DxFormModule,
    DxFileManagerModule,
    DxPopupModule,
    DxTextBoxModule,
    DxFileUploaderModule,
    DxButtonModule,
    DxTileViewModule,
    DxListModule,
    DxTemplateModule,
    DxPopupModule,
    DxPopoverModule,
    DxVectorMapModule,
    DxPieChartModule,
    DxScrollViewModule,
  ],
  providers: [NotificationToolTip],
  bootstrap: []
})
export class AppDevExpressModule { }
